name: Build & Test
on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  compile:
    permissions:
      contents: read
      checks: write
      statuses: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Setup Java
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Compile with Maven
        run: mvn -e --batch-mode compile -T 1C

  verify:
    permissions:
      contents: read
      checks: write
      statuses: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [17, 23]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Setup Java
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Test with Maven
        env:
          JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
          VONAGE_API_KEY: a1b2c3d4
          VONAGE_API_SECRET: 1234567890abcdef
          VONAGE_SIGNATURE_SECRET: abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQR
          VONAGE_APPLICATION_ID: 00000000-0000-4000-8000-000000000000
          VONAGE_PRIVATE_KEY_PATH: src/test/resources/com/vonage/client/kt/application_key
        run: mvn -e --batch-mode clean verify -T 1C
      - name: Run Codecov
        uses: codecov/codecov-action@288befbd1044bd1756afb0bdae077549e0ddb31f
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
